# Generated by Django 2.2.28 on 2023-03-05 21:37

import bookShare.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookShare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(13), django.core.validators.MinLengthValidator(13)])),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=bookShare.models.rename_book)),
                ('title', models.CharField(max_length=128)),
                ('genre', models.CharField(max_length=128)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('is_reserved', models.BooleanField(default=False)),
                ('publisher_id', models.ManyToManyField(to='bookShare.Publisher')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookShare.UserProfile')),
            ],
        ),
    ]
