# Generated by Django 2.2.28 on 2023-03-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookShare', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(),
        ),
    ]
