# Generated by Django 2.2.28 on 2023-03-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookShare', '0003_auto_20230305_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_follows_+', to='bookShare.UserProfile'),
        ),
    ]
