# Generated by Django 2.2.28 on 2023-03-17 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookShare', '0011_auto_20230317_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='book_id',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='interest',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookShare.Book'),
        ),
    ]
