# Generated by Django 2.2.28 on 2023-03-17 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookShare', '0012_auto_20230317_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intrest',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookShare.Book'),
        ),
    ]
