# Generated by Django 2.2.28 on 2023-03-18 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookShare', '0016_auto_20230318_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookShare.Book'),
        ),
    ]
