# Generated by Django 2.2.28 on 2023-03-20 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookShare', '0018_auto_20230318_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reserved_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_user', to='bookShare.UserProfile'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookShare.Book'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='post_code',
            field=models.CharField(max_length=7),
        ),
    ]
