# Generated by Django 2.2.28 on 2023-03-20 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookShare', '0022_auto_20230320_2026'),
        ('bookShare', '0022_auto_20230320_1817'),
    ]

    operations = [
    ]
