# Generated by Django 2.2.28 on 2023-03-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookShare', '0025_auto_20230321_0147'),
        ('bookShare', '0024_auto_20230321_1109'),
    ]

    operations = [
    ]
