# Generated by Django 2.2.28 on 2023-03-21 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookShare', '0026_merge_20230321_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookShare.Book'),
        ),
    ]
