# Generated by Django 2.2.28 on 2023-03-21 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookShare', '0027_auto_20230321_1342'),
        ('bookShare', '0024_auto_20230321_1056'),
    ]

    operations = [
    ]
